Enchantments, a handful of bug fixes
DragonSurvivalTeam/DragonSurvival pull request #599
Opened 2024-07-20 10:05 UTC by Psither

The first pass at having items that have built-in enchantments that can't be removed, but don't block normal enchanting logic

Fixes silk touch giving dragon dust items
Fixes a body type not being assigned properly when using the dragon command without specifying it
Fixes base body type not specifying health bonus

2024-07-20 10:17 UTC, SiverDX commented
is `getDefaultEnchantments` only called on the client?

How is the server going to determine the default enchantments?
Why not pass a level / registry access to the method, don't the events have access to that (level or an entity)?

Also would recommend adding a new method to 
https://github.com/DragonSurvivalTeam/DragonSurvival/blob/1.21.x/src/main/java/by/dragonsurvivalteam/dragonsurvival/util/EnchantmentUtils.java
which gets an enchantment, to cut down on boilerplate code

2024-07-20 10:35 UTC, Psither commented
ItemStack doesn't have any way to access the level directly, or any entities to get the level from, and that's all that most of these methods get.

2024-07-20 10:41 UTC, SiverDX commented
I mean at the moment it just wouldn't work, would it?
In `applyDebuffs` you have an entity but still access the client minecraft instance
(and iirc effects can only really be modified on the server side)

same for the `livingHurt` event

you could maybe popualte a static list on `ServerStartedEvent` (if the server has registry access, don't know tbh)

2024-07-20 18:03 UTC, seelderr requested changes

2024-07-20 18:03 UTC, seelderr commented on src/main/java/by/dragonsurvivalteam/dragonsurvival/common/items/armor/DragonHunterSword.java
> +                    .getHolderOrThrow(DSEnchantments.DRAGONSBANE), 3);
I was thinking about naming a special sword Dragonsbane, but the enchantment I would just call Bane of Dragons to match up with vanilla names

2024-07-20 18:03 UTC, seelderr commented on src/main/java/by/dragonsurvivalteam/dragonsurvival/mixins/MixinGrindstoneMenu.java
> +    private void addDefaultEnchantmentsBack(ItemStack pItem, CallbackInfoReturnable<ItemStack> cir) {
Is this the part where it does remove only non-permanent enchants?

2024-07-20 18:03 UTC, seelderr commented on src/main/java/by/dragonsurvivalteam/dragonsurvival/registry/DSEnchantments.java
> +    public static ResourceKey<Enchantment> CURSE_OF_OUTLAW = register("curse_of_outlaw");
"Curse of Outlaws" ?

2024-07-21 03:19 UTC, TeamSpen210 commented
Instead of directly adding enchantments to NBT, it might be better to instead override [`getEnchantmentLevel()`](https://github.com/neoforged/NeoForge/blob/c636694bd5135d520c7b162d7b38f00cfc583364/src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java#L448) and `getAllEnchantments()`. That way the item is considered to  have the enchantment for gameplay purposes, but it can't be removed with the grindstone, regular enchantments can still work, etc.

2024-07-21 07:07 UTC, Psither commented on src/main/java/by/dragonsurvivalteam/dragonsurvival/registry/DSEnchantments.java
> +    public static ResourceKey<Enchantment> CURSE_OF_OUTLAW = register("curse_of_outlaw");
Placeholder value

2024-07-21 23:33 UTC, seelderr approved these changes

2024-07-21 23:33 UTC, merged